// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReceiver creates a new instance of MockReceiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceiver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceiver {
	mock := &MockReceiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReceiver is an autogenerated mock type for the Receiver type
type MockReceiver struct {
	mock.Mock
}

type MockReceiver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceiver) EXPECT() *MockReceiver_Expecter {
	return &MockReceiver_Expecter{mock: &_m.Mock}
}

// C provides a mock function for the type MockReceiver
func (_mock *MockReceiver) C() <-chan transport.Message {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for C")
	}

	var r0 <-chan transport.Message
	if returnFunc, ok := ret.Get(0).(func() <-chan transport.Message); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan transport.Message)
		}
	}
	return r0
}

// MockReceiver_C_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'C'
type MockReceiver_C_Call struct {
	*mock.Call
}

// C is a helper method to define mock.On call
func (_e *MockReceiver_Expecter) C() *MockReceiver_C_Call {
	return &MockReceiver_C_Call{Call: _e.mock.On("C")}
}

func (_c *MockReceiver_C_Call) Run(run func()) *MockReceiver_C_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReceiver_C_Call) Return(messageCh <-chan transport.Message) *MockReceiver_C_Call {
	_c.Call.Return(messageCh)
	return _c
}

func (_c *MockReceiver_C_Call) RunAndReturn(run func() <-chan transport.Message) *MockReceiver_C_Call {
	_c.Call.Return(run)
	return _c
}

// SendGracefulShutdownCompleted provides a mock function for the type MockReceiver
func (_mock *MockReceiver) SendGracefulShutdownCompleted() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendGracefulShutdownCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceiver_SendGracefulShutdownCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendGracefulShutdownCompleted'
type MockReceiver_SendGracefulShutdownCompleted_Call struct {
	*mock.Call
}

// SendGracefulShutdownCompleted is a helper method to define mock.On call
func (_e *MockReceiver_Expecter) SendGracefulShutdownCompleted() *MockReceiver_SendGracefulShutdownCompleted_Call {
	return &MockReceiver_SendGracefulShutdownCompleted_Call{Call: _e.mock.On("SendGracefulShutdownCompleted")}
}

func (_c *MockReceiver_SendGracefulShutdownCompleted_Call) Run(run func()) *MockReceiver_SendGracefulShutdownCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReceiver_SendGracefulShutdownCompleted_Call) Return(err error) *MockReceiver_SendGracefulShutdownCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceiver_SendGracefulShutdownCompleted_Call) RunAndReturn(run func() error) *MockReceiver_SendGracefulShutdownCompleted_Call {
	_c.Call.Return(run)
	return _c
}
